language: python
python: 2.7
services:
  - mysql
env:
  - DJANGO_SETTINGS_MODULE="cliques.settings"
env:
  - TOX_ENV=django
  - TOX_ENV=flake8
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
before_script:
  - mysql -e 'create database cliques;'
  - python manage.py syncdb --noinput
  - python manage.py migrate
