application: cliquesio
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: django
  version: "1.5"
- name: MySQLdb
  version: "latest"

builtins:
- django_wsgi: on

handlers:
- url: /static/
  static_dir: staticfiles
- url: /.*
  script: cliques.wsgi.application

env_variables:
  DJANGO_SETTINGS_MODULE: 'cliques.settings'

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(lib/.*)
#- ^(libs/django/.*)
- ^(bin/.*)
- ^(share/.*)
- ^(include/.*)
- ^(.idea/.*)
- ^(.git/.*)